import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google"; // Import Open Sans
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: ["400", "700"], // Define the weights you need
});

export const metadata: Metadata = {
  title: "IDEATEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${geistSans.variable} ${geistMono.variable} bg-[#04000A] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
